version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./nextcloud/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasshere
      - MYSQL_PASSWORD=databasepasswordhere
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud/data:/var/www/html
    ports:
      - 80:80
    links:
      - db
    depends_on:
      - db

  haproxy:
    image: jclebreton/https-proxy
    container_name: haproxy
    restart: always
    ports:
      - 443:443
    links:
      - app
    depends_on:
      - app
    environment:
      - BACKEND_SERVER=app
      - BACKEND_PORT=80
